import { defineConfig } from 'steiger';
import fsd from '@feature-sliced/steiger-plugin';

// FSD linter: npm run lint:fsd
export default defineConfig([
  ...fsd.configs.recommended,
  {
    // generated by GraphQL Codegen, not our code
    ignores: ['**/shared/api/gql/**'],
  },
  {
    // most single-use slices get a second consumer later in the plan
    // (address → checkout, product-listing → search, login → checkout);
    // revisit at the end instead of merging and splitting them back
    rules: {
      'fsd/insignificant-slice': 'off',
    },
  },
]);
