export enum UrlRewriteEntityTypeEnum {
  BUNDLE_PRODUCT = 'BUNDLE_PRODUCT',
  CATEGORY = 'CATEGORY',
  CATEGORY_PRODUCT_LIST = 'CATEGORY_PRODUCT_LIST',
  CMS_PAGE = 'CMS_PAGE',
  CONFIGURABLE_PRODUCT = 'CONFIGURABLE_PRODUCT',
  GROUPED_PRODUCT = 'GROUPED_PRODUCT',
  PRODUCT = 'PRODUCT',
  SIMPLE_PRODUCT = 'SIMPLE_PRODUCT',
  VIRTUAL_PRODUCT = 'VIRTUAL_PRODUCT',
}
